# Services to enable after installation.
# Format: system|user <unit-name> <group>

# System services (desktop group)
system NetworkManager.service desktop
system bluetooth.service desktop
system sshd.service essentials
system ufw.service desktop

# System services (communication group)
system tailscaled.service communication
system mullvad-daemon.service communication

# System services (CachyOS)
system ananicy-cpp.service essentials
system avahi-daemon.service desktop
system fstrim.timer essentials
system snapper-cleanup.timer essentials

# User services (desktop group)
user wireplumber.service desktop
user pipewire.socket desktop
user pipewire-pulse.socket desktop
user xdg-user-dirs.service desktop
user arch-update-tray.service desktop
user arch-update.timer desktop
